version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress

    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  ftp-server:
    build: requirements/bonus/ftp_server
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - network
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

  adminer:
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - network

  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    restart: always
    networks:
      - network

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: always
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/agimi/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/agimi/data/wordpress
      o: bind

networks:
  network:
    driver: bridge